# This is a basic workflow to help you get started with Actions

name: Say Hello on Docker

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Hello rold action step
        uses: ./actions/hello-world-docker-action
        id: hello
        with:
          who-to-great: 'Mona the Octocat'
      
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"

